### ISSUE TITLE
InvalidCastException when named registrations are used

### ISSUE THREAD

**Issue by davisnw** [MRCollective/MiniProfiler.DeepProfiling.Autofac#1]
When I do a named registration (I happen to be doing a decorator also, as described at http://nblumhardt.com/2011/01/decorator-support-in-autofac-2-4/, e.g.

```
> builder.RegisterType<CommandHandler>()
>     .Named<ICommandHandler>("implementor");
> 
> builder.RegisterDecorator<ICommandHandler>(
>         (c, inner) => new TransactedCommandHandler(inner, c.Resolve<ISession>()),
>         fromKey: "implementor");
```

Then the following exception occurs:

> Unable to cast object of type 'Autofac.Core.KeyedService' to type 'Autofac.Core.TypedService'.
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
> 
> Exception Details: System.InvalidCastException: Unable to cast object of type 'Autofac.Core.KeyedService' to type 'Autofac.Core.TypedService'.
> 
> Source Error:
> 
> An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
> 
> Stack Trace:
> 
> [InvalidCastException: Unable to cast object of type 'Autofac.Core.KeyedService' to type 'Autofac.Core.TypedService'.]
>    StackExchange.Profiling.DeepProfiling.Autofac.<>c__DisplayClass3.<AttachToComponentRegistration>b__1(Service s) in c:\Users\233665i\Documents\Visual Studio 2012\Projects\MiniProfiler.DeepProfiling.Autofac\MiniProfiler.DeepProfiling.Autofac\MiniProfilingInterceptionModule.cs:25
>    System.Linq.WhereSelectListIterator`2.MoveNext() +103
>    System.Linq.WhereEnumerableIterator`1.MoveNext() +85
>    System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +381
>    System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
>    StackExchange.Profiling.DeepProfiling.Autofac.<>c__DisplayClass3.<AttachToComponentRegistration>b__0(Object sender, ActivatingEventArgs`1 e) in c:\Users\233665i\Documents\Visual Studio 2012\Projects\MiniProfiler.DeepProfiling.Autofac\MiniProfiler.DeepProfiling.Autofac\MiniProfilingInterceptionModule.cs:25
>    Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable`1 parameters, Object& instance) +127
>    Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +230
>    Autofac.Core.Resolving.InstanceLookup.<Execute>b__0() +63
>    Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator) +201
>    Autofac.Core.Resolving.InstanceLookup.Execute() +262
>    Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +282
>    Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +72
>    Autofac.Features.LightweightAdapters.<>c__DisplayClass9.<RegistrationsFor>b__1(IComponentContext c, IEnumerable`1 p) +118
>    Autofac.Builder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) +59
>    Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +191
>    Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +109
>    Autofac.Core.Resolving.InstanceLookup.Execute() +158
>    Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +282
>    Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +72
>    Autofac.Core.Activators.Reflection.<>c__DisplayClass2.<CanSupplyValue>b__0() +82
>    Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() +233
>    Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +589
>    Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) +109
>    Autofac.Core.Resolving.InstanceLookup.Execute() +158
>    Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +282
>    Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +60
>    Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) +73
> 
> [DependencyResolutionException: An exception was thrown while executing a resolve operation. See the InnerException for details. ---> Unable to cast object of type 'Autofac.Core.KeyedService' to type 'Autofac.Core.TypedService'. (See inner exception for details.)]
>    Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) +177
>    Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +279
>    Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) +175
>    Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) +242
>    Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters) +72
>    Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType) +48
>    Autofac.Integration.Mvc.AutofacDependencyResolver.GetService(Type serviceType) +57
>    System.Web.Mvc.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType) +87

**Comment by MattDavies** [comment]
Fixed by #2
